// packages/automerge-repo-react-hooks/src/usePresence.ts
import { useCallback, useEffect, useState } from "react"

import {
  DocHandle,
  Presence,
  PeerPresenceStates,
  LocalState,
  PresenceOpts,
} from "@automerge/automerge-repo/slim"
import { useInvalidate } from "./helpers/useInvalidate.js"

export type UsePresenceResult<State, Channel extends keyof State> = {
  peerStates: PeerPresenceStates<State>
  localState: LocalState<State>
  update: (channel: Channel, value: State[Channel]) => void
}

export function usePresence<State, Channel extends keyof State>(
  handle: DocHandle<unknown>,
  userId: string,
  deviceId: string,
  initialState: State,
  opts?: PresenceOpts
): UsePresenceResult<State, Channel> {
  const invalidate = useInvalidate()
  const [presence] = useState(() => {
    const presence = new Presence(handle, userId, deviceId, initialState, opts)
    presence.on("heartbeat", invalidate)
    presence.on("state", invalidate)
    presence.on("goodbye", invalidate)
    return presence
  })

  useEffect(() => {
    return () => presence.dispose()
  }, [presence])

  const updateLocalState = useCallback(
    (channel: Channel, msg: State[Channel]) => {
      presence.broadcast(channel, msg)
    },
    [presence]
  )

  return {
    peerStates: presence.getPeerStates(),
    localState: presence.getLocalState(),
    update: updateLocalState,
  }
}

// packages/automerge-repo-solid-primitives/src/usePresence.ts
import {
  type DeviceId,
  type DocHandle,
  PeerStateView,
  Presence,
  type PresenceConfig,
  type PresenceState,
  type UserId,
} from "@automerge/automerge-repo/slim"
import { type Accessor, createSignal, onCleanup, onMount } from "solid-js"

export type UsePresenceConfig<State extends PresenceState> =
  PresenceConfig<State> & {
    handle: DocHandle<unknown>
    userId?: UserId
    deviceId?: DeviceId
  }

export type UsePresenceResult<State extends PresenceState> = {
  peerStates: Accessor<PeerStateView<State>>
  localState: Accessor<State> | undefined
  update: <Channel extends keyof State>(
    channel: Channel,
    value: State[Channel]
  ) => void
  start: () => void
  stop: () => void
}

export function usePresence<State extends PresenceState>({
  handle,
  userId,
  deviceId,
  initialState,
  heartbeatMs,
  peerTtlMs,
}: UsePresenceConfig<State>): UsePresenceResult<State> {
  const [localState, setLocalState] = createSignal<State>(initialState)
  const [peerStates, setPeerStates] = createSignal(new PeerStateView<State>({}))
  const [presence] = createSignal(
    new Presence<State>({ handle, userId, deviceId })
  )

  onMount(() => {
    const presenceHandle = presence()
    presenceHandle.start({
      initialState,
      heartbeatMs,
      peerTtlMs,
    })

    presenceHandle.on("heartbeat", () =>
      setPeerStates(presenceHandle.getPeerStates())
    )
    presenceHandle.on("snapshot", () =>
      setPeerStates(presenceHandle.getPeerStates())
    )
    presenceHandle.on("update", () =>
      setPeerStates(presenceHandle.getPeerStates())
    )
    presenceHandle.on("goodbye", () =>
      setPeerStates(presenceHandle.getPeerStates())
    )
  })

  onCleanup(() => {
    presence().stop()
  })

  const update = <Channel extends keyof State>(
    channel: Channel,
    msg: State[Channel]
  ) => {
    presence().broadcast(channel, msg)
    const updated = presence().getLocalState()
    setLocalState(() => updated)
  }

  const start = () => {
    presence().start({
      initialState: presence().getLocalState(),
      heartbeatMs,
      peerTtlMs,
    })
  }

  const stop = () => {
    presence().stop()
  }

  return {
    localState,
    peerStates,
    update,
    start,
    stop,
  }
}
