// packages/automerge-repo-react-hooks/src/useRepo.ts
import { Repo } from "automerge-repo"
import { createContext, useContext } from "react"

export const RepoContext = createContext<Repo | null>(null)

export function useRepo(): Repo {
  const repo = useContext(RepoContext)
  if (!repo) throw new Error("Repo was not found on RepoContext.")
  return repo
}

// packages/automerge-repo-solid-primitives/src/useRepo.ts
import type { Repo } from "@automerge/automerge-repo/slim"
import { RepoContext } from "./context.js"
import { useContext } from "solid-js"

/** grab the repo from the {@link RepoContext} */
export default function useRepo(): Repo {
  const repo = useContext(RepoContext)
  if (!repo) throw new Error("Please wrap me in a <RepoContext value={repo}>")
  return repo
}
